# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-08 12:54
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Instrutor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fone', models.CharField(max_length=13, verbose_name='Telefone')),
                ('whatsapp', models.CharField(max_length=13, verbose_name='Whatsapp')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Instrutor')),
            ],
            options={
                'verbose_name': 'Instrutor',
                'ordering': ['user'],
                'verbose_name_plural': 'Instrutores',
            },
        ),
    ]
