# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-06 18:48
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome Completo')),
                ('data_nascimento', models.DateField(verbose_name='Data de nascimento')),
                ('fone', models.CharField(max_length=13, verbose_name='Telefone')),
                ('whatsapp', models.CharField(max_length=13, verbose_name='Whatsapp')),
                ('cidade', models.CharField(max_length=255, verbose_name='Cidade')),
                ('estado', models.CharField(max_length=255, verbose_name='Estado')),
                ('bairro', models.CharField(max_length=255, verbose_name='Bairro')),
                ('data_criacao', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data de criação')),
                ('data_atualizacao', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data de atualização')),
            ],
            options={
                'verbose_name': 'Aluno',
                'verbose_name_plural': 'Alunos',
            },
        ),
        migrations.CreateModel(
            name='Aula',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aula', models.CharField(max_length=255, verbose_name='Descriminação da aula')),
                ('data', models.DateField(verbose_name='Data da aula')),
                ('data_criacao', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data de criação')),
                ('data_atualizacao', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data de atualização')),
            ],
            options={
                'verbose_name': 'Aula',
                'verbose_name_plural': 'Aulas',
            },
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curso', models.CharField(choices=[('Conheça o espiritísmo', 'Conheça o espiritísmo'), ('Nosso Lar', 'Nosso Lar'), ('Passe', 'Passe'), ('Corrente Magnética', 'Corrente Magnética')], default=1, max_length=255, verbose_name='Curso')),
            ],
            options={
                'verbose_name': 'Curso',
                'verbose_name_plural': 'Cursos',
                'ordering': ['curso'],
            },
        ),
        migrations.CreateModel(
            name='Frequencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequencia', models.BooleanField(default=1)),
                ('data_criacao', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data de criação')),
                ('data_atualizacao', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data de atualização')),
                ('aluno', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Aluno', verbose_name='Aluno')),
                ('aula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Aula')),
            ],
            options={
                'verbose_name': 'Frequência',
                'verbose_name_plural': 'Frequências',
                'ordering': ['aula'],
            },
        ),
        migrations.CreateModel(
            name='Situacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequencia', models.IntegerField(blank=True, default=0, null=True)),
                ('situacao', models.CharField(choices=[('1', 'Apto'), ('2', 'Inapto por frequência')], default='1', max_length=255, verbose_name='Situação')),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Aluno')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Curso')),
            ],
            options={
                'verbose_name': 'Situação',
                'verbose_name_plural': 'Situação',
                'ordering': ['aluno', 'curso'],
            },
        ),
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turma', models.IntegerField(verbose_name='Período da turma')),
                ('limite_faltas', models.IntegerField(default=2, verbose_name='Limite de faltas')),
                ('data_inicio', models.DateField(verbose_name='Data de início')),
                ('data_termino', models.DateField(verbose_name='Data de término')),
                ('data_criacao', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data de criação')),
                ('data_atualizacao', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data de atualização')),
                ('aluno', models.ManyToManyField(blank=True, null=True, to='core.Aluno')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Curso')),
                ('instrutor', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Turma',
                'verbose_name_plural': 'Turmas',
                'ordering': ['turma'],
            },
        ),
        migrations.AddField(
            model_name='aula',
            name='turma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Turma'),
        ),
        migrations.AlterUniqueTogether(
            name='turma',
            unique_together=set([('curso', 'turma')]),
        ),
        migrations.AlterUniqueTogether(
            name='frequencia',
            unique_together=set([('aula', 'aluno')]),
        ),
    ]
