# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-21 22:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_turma_ativo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turma',
            name='data_inicio',
            field=models.DateTimeField(verbose_name='Data de início'),
        ),
        migrations.AlterField(
            model_name='turma',
            name='data_termino',
            field=models.DateTimeField(verbose_name='Data de término'),
        ),
    ]
