# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-25 23:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20160821_1936'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='situacao',
            options={'ordering': ['aluno', 'turma'], 'verbose_name': 'Situação', 'verbose_name_plural': 'Situação'},
        ),
        migrations.RemoveField(
            model_name='situacao',
            name='curso',
        ),
        migrations.AddField(
            model_name='situacao',
            name='turma',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.Turma'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='turma',
            name='aluno',
            field=models.ManyToManyField(blank=True, to='core.Aluno'),
        ),
    ]
