# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-26 02:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20160825_2309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turma',
            name='data_atualizacao',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data de atualização'),
        ),
        migrations.AlterField(
            model_name='turma',
            name='data_criacao',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data de criação'),
        ),
    ]
