# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-31 21:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20160831_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turma',
            name='turma',
            field=models.IntegerField(choices=[('1', '2016.1'), ('2', '2016.2'), ('3', '2016.3')], default='1', verbose_name='Período da Turma'),
        ),
    ]
